# Generated by Django 3.1.1 on 2020-09-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(help_text='Language Codes according to <a href="http://www.mathguide.de/info/tools/languagecode.html">ISO 639-1</a>', max_length=3)),
                ('language_name', models.CharField(help_text='Enter a book genre (e.g. Science Fiction)', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(help_text='Select a language of that book', to='Catalog.Translation'),
        ),
    ]
